### ISSUE TITLE
Elección de módulos

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#1]
# ft_transcendence

## Parte inicial: Modulos que yo haría si o si

- Framework module: para tener un framework de backend y no tener que escribirlo en ruby.
- Database module: bastante esencial creo yo para implementar luego otros módulos.
- Frontent module: este es un poco más opcional, pero nos dan puntos por utilizar bootstrap, si no habría que hacerlo en JavaScript vanilla y CSS pelado.
- Remote players module: para que los jugadores puedan jugar online.
- Standard User Management module: registro de usuarios, si implementamos el multijugador online también habría que implementar este creo yo.

Para aprobar hay que implementar 7 módulos mayores, y para el bonus son 2 mayores y 1 menor o más.

## Módulos específicos

Como 2 módulos menores equivalen a 1 mayor, voy a poner +1 para módulos mayores y +0.5 
para menores.

### Usar el framework de backend: +1

Implementar Django como backend del proyecto

### Usar el framework de frontend: +0.5

Utilizar bootstrap para el diseño del frontend

### Usar base de datos para el backend: +0.5

Se nos pide implementar PostgreSQL para la BBDD

### Autenticación y registro de usuarios: +1

Todo lo relativo al registro, login, modificacion de usuarios, subir avatares, 
historial de partidas, etc

### Jugadores online: +1

Implementar multijugador online y todo lo que conlleva

### Más de 2 jugadores en la misma partida: +1?

Hacer un modo de juego en el que en lugar de ser 1vs1 sea 2vs2 por ejemplo.

### Chat en directo: +1

Enviar mensajes, bloquear usuarios, invitar a partida, etc.

### Oponente con IA: +1

Crear un jugador que sea la máquina, y que sea bueno

### Implementar técnicas avanzadas de 3D: +1

Crear el juego de Pong utilizando ThreeJS/WebGL.

# Conclusión

Con los módulos que he marcado tenemos 7 u 8, dependiendo de si queremos hacer el pong de más de 2 jugadores, pero quiero que reviseis vosotros también tanto los que he puesto yo como los que vienen en el subject. Hay otros que también son interesantes como los de DevOps o el de implementar un pong que se ejecute en la línea de comandos también.

Decidme si veis bien los que he puesto y añadid cada uno 3 módulos más por si los queremos hacer para el bonus o cambiar alguno de los que tenemos ahora mismo.

Os toca @andresja75 @jlimonesHer @SergioDiazDev @albertobarriga

**Comment by andresja75** [comment]
Yo creo que están bien los que has puesto.
Yo añadiría:
- Autenticación de 2 factores y jwt (Módulo mayor de Ciberseguridad)
- Opciones de customización del juego (Módulo menor de Gameplay)

Y quizás algo de devops como ha dicho Fran:
- Configuración de la estructura para gestión de registros (Módulo mayor de DevOps)
