### ISSUE TITLE
AI Opponent Module: Implementar un rival con IA: +1.0

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#10]
En este módulo principal, el objetivo es incorporar un jugador de IA al juego. Para esta tarea no está permitido el uso del algoritmo A*.

- [x] Desarrollar un oponente de IA que proporcione una experiencia de juego desafiante y atractiva experiencia de juego para los usuarios.
- [x] La IA debe replicar el comportamiento humano, lo que significa que en su implementación de IA, debe simular la entrada del teclado. La restricción aquí es que la IA sólo puede actualizar su visión del juego una vez por segundo, lo que le obliga a anticiparse a los rebotes y otras acciones.
- [x] La IA debe utilizar potenciadores si has elegido implementar el módulo Módulo de opciones de personalización del juego.
- [x] Implementar la lógica de la IA y los procesos de toma de decisiones que permitan al jugador de la IA realizar movimientos inteligentes y estratégicos.
- [x] Explora algoritmos y técnicas alternativas para crear un jugador de IA eficaz sin depender de A*.
- [x] Garantizar que la IA se adapte a diferentes escenarios de juego e interacciones del usuario.

**Comment by emartinez-dev** [comment]
Me gustaría implementar este módulo a mi ya que me parece bastante interesante y ya sé algo de Python y Machine Learning

**Comment by albertobarriga** [comment]
Me gustaría ayudar con este módulo, ya que he tocado algo python con librerias de IA.

**Comment by SergioDiazDev** [comment]
Me añado a este proyecto, por curiosidad y por si os puedo echar una mano.
