### ISSUE TITLE
Backend Module: Implementar Django como backend del proyecto: +1.0

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#4]

**Comment by emartinez-dev** [comment]
No tengo mucha idea de Backend ni de Django pero sí que he programado algo usando Python y PostgreSQL, podría echaros una mano con esto

**Comment by andresja75** [comment]
Esta no es muy complicada la verdad, implementar el backend en django es simplemente usar django, en autenticació, websockets así que yo creo que esta ya va implícita en los modulos que he cogido.

**Comment by emartinez-dev** [comment]
Vale, pues te encargas tú de dirigir un poco la parte de backend, ya que lo tendremos que tocar todos de alguna u otra forma
