### ISSUE TITLE
Frontend Module: Utilizar bootstrap para el diseño del frontend: +0.5

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#5]

**Comment by emartinez-dev** [comment]
No sé mucho de frontend pero sí que os puedo echar una mano creando un mockup en Figma por ejemplo

**Comment by jlimonesHer** [comment]
Enrique me pones por aqui el enlace a figma ?
Para tener acceso al diseño.

**Comment by emartinez-dev** [comment]
Si claro, aqui llevas:

https://www.figma.com/file/ouUHlVCQQ8L3T6nfi29ZS8/Transcendence?type=design&node-id=32416%3A3014&mode=design&t=xhT46mTR0nnBCoqw-1

**Comment by emartinez-dev** [comment]
Recursos para hacer Django una SPA:

https://forum.djangoproject.com/t/turning-mpa-to-spa/27692
https://github.com/django-webpack/django-webpack-loader
https://github.com/metakermit/django-spa

**Comment by emartinez-dev** [comment]
@jlimonesHer @SergioDiazDev @albertobarriga @andresja75 ya está la SPA hecha, para que los links se recorran a través de la SPA y no con el funcionamiento normal de un link hay que ponerle un atributo **link** dentro del enlace tal que así:

Enlace sin SPA: `<a href="/profile">Profile</a>`
Enlace con SPA: `<a link href="/profile">Profile</a>`
