### ISSUE TITLE
User Management Module: Autenticación, registro y gestión de usuarios: +1.0

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#7]
Requisitos del módulo:

- [x] Los usuarios pueden registrarse en el sitio web de forma segura.
- [x] Los usuarios registrados pueden iniciar sesión de forma segura.
- [x] Los usuarios pueden seleccionar un nombre de usuario único para jugar en los torneos.
- [x] Los usuarios pueden actualizar su información.
- [x] Los usuarios pueden subir un avatar, con una opción por defecto si no se proporciona ninguno.
- [x] Los usuarios pueden añadir a otros como amigos y ver su estado en línea.
- [x] Los perfiles de usuario muestran estadísticas, como victorias y derrotas.
- [x] Cada usuario tiene un Historial de Partidas que incluye partidas 1v1, fechas y detalles relevantes, accesibles para los usuarios conectados.
- [x] Manejar nombres de usuarios y/o emails duplicados, lo podemos hacer como queramos pero hay que justificar la respuesta.

**Comment by andresja75** [comment]
Esta la puedo hacer yo que ya había mirado previamente como hacerla en nest js, solo es adaptarla a django.
