### ISSUE TITLE
Live Chat Module: Enviar mensajes, bloquear usuarios, invitar a partida, etc: + 1.0

### ISSUE THREAD

**Issue by emartinez-dev** [andresja75/ft_transcendence#9]
En este módulo hay que crear un chat para los usuarios:

- [x] El usuario debe poder enviar mensajes directos a otros usuarios.
- [x] El usuario debe poder bloquear a otros usuarios. De esta manera, no verán más mensajes de la cuenta que bloquearon.
- [x] El usuario debe poder invitar a otros usuarios a jugar una partida de Pong a través de la interfaz de chat.
- [x] El sistema de torneos debería poder avisar a los usuarios esperados para la siguiente partida.
- [x] El usuario debe poder acceder a los perfiles de otros jugadores a través de la interfaz de chat.

**Comment by andresja75** [comment]
Esta también la tengo mirada ya de hace tiempo, me puedo encargar.
